### PR TITLE
Fix: Ensure hidden attribute works as expected

### LINKED ISSUE #8: NFR: Create way to easily activate/deactivate or hide/unhide bar and spinner
Right now if I want to add an indefinite progress bar that only shows during an action like a search, I need to add and remove the element form the DOM.

To show I'm having to do something like:
```
let progress = document.createElement('vaadin-progress-bar');
progress.id = 'searchProgress';
this.$.searchFormDiv.appendChild(progress);
```
and then when my action finishes, I do
```
this.shadowRoot.querySelector('#searchProgress').remove();
```
not overly intuitive. It would be nice if it had something similar to `paper-spinner` where I can set `hidden` and `active` attributes that govern the visibility and/or active state of the bar. With the ability to have an indefinite `value`, perhaps only something like an `active` property is needed.

### PR DESCRIPTION
**Pull request by stramel**
Fixes #8 

[hidden.is.a.lie.fyi](hidden.is.a.lie.fyi)

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-progress-bar/10)

### CODE REVIEW

**Comment by manolo** [comment]
hidden should be handled by the browser by setting `display: hidden` when the attribute is true.
But that happens unless there is a specific value for the display, which in these elements is `block`
As a norma we set the display to some value for the `:host` of all our elements. I think we should then align all vaadin elements and add an additional rule for `:host[hidden]`, otherwise we should not set to any of our elements and let the user do it in their custom css. As reference in many paper elements they have the rule for hidden (paper-badge/button/checkbox/input/textarea/progress...)  @jouni @tomivirkki  WDYT? 

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-progress-bar/10#-:-Kw3k0q8o-xI5b-AA0HK:brlsdf8)*

**Comment by jouni** [comment]
I agree with @manolo (and @stramel) that we should add these rules explicitly to all of our elements.

**Comment by jouni** [comment]
@Toshegg, please update this PR (drop the circle related styles) and merge.

**Comment by tonygoldcrest** [comment]
Closed in favour of #25

**Pull request closed without merging**
