### PR TITLE
Accessibility

### PR DESCRIPTION
**Pull request by tonygoldcrest**
Added role, tabindex, aria-valuenow, aria-valuemin, aria-valuemax attributes.
Connects to #11

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-progress-bar/18)

### CODE REVIEW

**Comment by limonte** [comment]
did you try this change with some screen reader?

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-progress-mixin.html, line 51 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-progress-bar/18#-Kw4CVEiJs2MbArvh3yH:-Kw4CVEiJs2MbArvh3yI:bod3a4l) ([raw file](https://github.com/vaadin/vaadin-progress-bar/blob/7c50159e88074590bcbc052f0cf547e53d04d4d3/vaadin-progress-mixin.html#L51)):*
> ```HTML
>         super.ready();
> 
>         this.setAttribute('tabindex', 0);
> ```

I don't think we want progress-bar to be in taborder (focusable with keyboard)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-progress-bar/18#-:-Kw4CbGbW3rntkv0Mdgg:b-qyxvu4)*

**Comment by tonygoldcrest** [comment]
@limonte, I've tried with Voice Over. Works perfect

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-progress-mixin.html, line 51 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-progress-bar/18#-Kw4CVEiJs2MbArvh3yH:-Kw4WQIWiXWolrx12HD7:b-896fix) ([raw file](https://github.com/vaadin/vaadin-progress-bar/blob/7c50159e88074590bcbc052f0cf547e53d04d4d3/vaadin-progress-mixin.html#L51)):*
<details><summary><i>Previously, limonte (Limon Monte) wrote…</i></summary><blockquote>

I don't think we want progress-bar to be in taborder (focusable with keyboard)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-progress-bar/18#-:-Kw4WRWOSoUcQu3bmIia:b-q6b95b)*

**Comment by limonte** [comment]
> I've tried with Voice Over. Works perfect

Nit: VoiceOver, one word :) 

---

Nice work! :lgtm:  

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-progress-bar/18#-:-Kw4Xuprgbwl4NzdKl_v:bgd1hk5)*

**Comment by tomivirkki** [comment]
*[vaadin-progress-mixin.html, line 61 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-progress-bar/18#-Kw4YJWt7AsuSEdg-kGy:-Kw4YJWurOxHEzwMV_7f:b-dhx9bp) ([raw file](https://github.com/vaadin/vaadin-progress-bar/blob/f28738a57be0a7f7e5501bb67602309d33da1dfa/vaadin-progress-mixin.html#L61)):*
> ```HTML
> 
>       _valueChanged(newV, oldV) {
>         this.setAttribute('aria-valuenow', this.value);
> ```

Why does this need a new observer (why not just include this in the existing multi-value observer)? Also, `this.value` is the same as `newV` so the latter could be used instead

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-progress-bar/18)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-progress-bar/18#-:-Kw4dBgIDyEQ-OZuLkxC:bnfp4nl)*

**Pull request merged**
