### PR TITLE
Added themable mixin.

### PR DESCRIPTION
**Pull request by tonygoldcrest**
Also removed indeterminate demo.
Connects to #11

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-progress-bar/16)

### CODE REVIEW

**Comment by manolo** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[vaadin-progress-bar-styles.html, line 1 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-progress-bar/16#-Kw08jjvkRiHvvAHBd-i:-Kw08jjvkRiHvvAHBd-j:b-ce5g1p) ([raw file](https://github.com/vaadin/vaadin-progress-bar/blob/70e62dd9495e2362b4af8acbac64b1679b04bfb4/vaadin-progress-bar-styles.html#L1)):*
> ```HTML
> <dom-module id="vaadin-progress-bar-default-theme" theme-for="vaadin-progress-bar">
> ```

is it necessary to externalise this file ? I think it's so simple that could be in the same html.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-progress-bar/16)*

**Comment by tomivirkki** [comment]
PR should connect to #11?

**Comment by tonygoldcrest** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-progress-bar-styles.html, line 1 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-progress-bar/16#-Kw08jjvkRiHvvAHBd-i:-Kw0BWVOEKS3TVz5brc8:b-896fix) ([raw file](https://github.com/vaadin/vaadin-progress-bar/blob/70e62dd9495e2362b4af8acbac64b1679b04bfb4/vaadin-progress-bar-styles.html#L1)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

is it necessary to externalise this file ? I think it's so simple that could be in the same html.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-progress-bar/16)*

**Comment by tomivirkki** [comment]
*[vaadin-progress-bar.html, line 53 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-progress-bar/16#-Kw0Blv4KWKbxEHrKz2r:-Kw0Blv4KWKbxEHrKz2s:br4n5ip) ([raw file](https://github.com/vaadin/vaadin-progress-bar/blob/1354f0048d4b01c16463cf6fe129750c653b810f/vaadin-progress-bar.html#L53)):*
> ```HTML
>     </style>
> 
>     <div id="bar" part="bar">
> ```

Also drop the id's. It's very likely that some app has an `#bar` or `#value` element and that might cause collisions

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-progress-bar/16)*

**Comment by tonygoldcrest** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-progress-bar.html, line 53 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-progress-bar/16#-Kw0Blv4KWKbxEHrKz2r:-Kw0CEXjvrlMIqcwqI2F:b-q0c6j) ([raw file](https://github.com/vaadin/vaadin-progress-bar/blob/1354f0048d4b01c16463cf6fe129750c653b810f/vaadin-progress-bar.html#L53)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Also drop the id's. It's very likely that some app has an `#bar` or `#value` element and that might cause collisions
</blockquote></details>

What if I use ids in tests?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-progress-bar/16)*

**Comment by tomivirkki** [comment]
*[vaadin-progress-bar.html, line 53 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-progress-bar/16#-Kw0Blv4KWKbxEHrKz2r:-Kw0CQDxPqlpFZW0W4fj:buqi7qn) ([raw file](https://github.com/vaadin/vaadin-progress-bar/blob/1354f0048d4b01c16463cf6fe129750c653b810f/vaadin-progress-bar.html#L53)):*
<details><summary><i>Previously, Toshegg wrote…</i></summary><blockquote>

What if I use ids in tests?
</blockquote></details>

You can use for example `progress.$$('[part="bar"]')` in tests.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-progress-bar/16)*

**Comment by tonygoldcrest** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[vaadin-progress-bar.html, line 53 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-progress-bar/16#-Kw0Blv4KWKbxEHrKz2r:-Kw43gcwQnxxVNoBJG4b:b-4pxr7h) ([raw file](https://github.com/vaadin/vaadin-progress-bar/blob/1354f0048d4b01c16463cf6fe129750c653b810f/vaadin-progress-bar.html#L53)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

You can use for example `progress.$$('[part="bar"]')` in tests.
</blockquote></details>

@tomivirkki, FYI, $$ method is not presented in Polymer 2. We should use element.shadowRoot.querySelector() instead.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-progress-bar/16)*

**Comment by tonygoldcrest** [comment]
Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-progress-bar.html, line 53 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-progress-bar/16#-Kw0Blv4KWKbxEHrKz2r:-Kw45syTZB8sDPEOo6x3:b-896fix) ([raw file](https://github.com/vaadin/vaadin-progress-bar/blob/1354f0048d4b01c16463cf6fe129750c653b810f/vaadin-progress-bar.html#L53)):*
<details><summary><i>Previously, Toshegg wrote…</i></summary><blockquote>

@tomivirkki, FYI, $$ method is not presented in Polymer 2. We should use element.shadowRoot.querySelector() instead.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-progress-bar/16)*

**Comment by limonte** [comment]
@Toshegg are you getting notifications from Travis about failing CI builds?

**Comment by limonte** [comment]
Review status: 0 of 6 files reviewed at latest revision, 7 unresolved discussions, some commit checks broke.

---

*[vaadin-progress-bar.html, line 83 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-progress-bar/16#-Kw49ZQCxUDRXsj_NY7a:-Kw49ZQCxUDRXsj_NY7b:bcy88ly) ([raw file](https://github.com/vaadin/vaadin-progress-bar/blob/93b2520d5cb036dff07ef5fd8a1f27a46f5d3fb3/vaadin-progress-bar.html#L83)):*
> ```HTML
>        *
>        * @memberof Vaadin
>        * @mixes Vaadin.ProgressMixin
> ```

add `@mixes Vaadin.ThemableMixin`

---

*[demo/progress-bar-basic-demos.html, line 43 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-progress-bar/16#-Kw49byOElh6CcxuVywS:-Kw49byOElh6CcxuVywT:bon5imc) ([raw file](https://github.com/vaadin/vaadin-progress-bar/blob/32c6cc0e2c65f5fbf7ccf376a6051ab01ab2b6ac/demo/progress-bar-basic-demos.html#L43)):*
> ```HTML
> 
> 
>     <h3>Indeterminate Progress Bar</h3>
> ```

Why this demo example was removed?

---

*[test/vaadin-progress-bar.html, line 7 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-progress-bar/16#-Kw49j7XF6cPbNQauH3X:-Kw49j7XF6cPbNQauH3Y:b-7t91jo) ([raw file](https://github.com/vaadin/vaadin-progress-bar/blob/93b2520d5cb036dff07ef5fd8a1f27a46f5d3fb3/test/vaadin-progress-bar.html#L7)):*
> ```HTML
>   <title>vaadin-progress-bar tests</title>
>   <script src="../../web-component-tester/browser.js"></script>
>   <link rel="import" href="../../polymer/polymer-element.html">
> ```

Why this import was added?

---

*[test/vaadin-progress-bar.html, line 34 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-progress-bar/16#-Kw49lSnk2Sd2HEpP8lJ:-Kw49lSnk2Sd2HEpP8lK:b-l6mwxj) ([raw file](https://github.com/vaadin/vaadin-progress-bar/blob/93b2520d5cb036dff07ef5fd8a1f27a46f5d3fb3/test/vaadin-progress-bar.html#L34)):*
> ```HTML
>       it('should have proper scale', () => {
>         progress.value = 0.1;
>         console.log(progress.shadowRoot);
> ```

remove

---

*[test/vaadin-progress-bar.html, line 36 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-progress-bar/16#-Kw49q7TYQ1JoywCTNtM:-Kw49q7TYQ1JoywCTNtN:b-8q02w4) ([raw file](https://github.com/vaadin/vaadin-progress-bar/blob/93b2520d5cb036dff07ef5fd8a1f27a46f5d3fb3/test/vaadin-progress-bar.html#L36)):*
> progress.shadowRoot.querySelector('[part="value"]')

This should be assigned to the `value` variable in the `beforeEach`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-progress-bar/16)*

**Comment by tonygoldcrest** [comment]
Review status: 0 of 6 files reviewed at latest revision, 7 unresolved discussions, some commit checks broke.

---

*[demo/progress-bar-basic-demos.html, line 43 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-progress-bar/16#-Kw49byOElh6CcxuVywS:-Kw4Am87rbFZEfKVwilH:b-e2umax) ([raw file](https://github.com/vaadin/vaadin-progress-bar/blob/32c6cc0e2c65f5fbf7ccf376a6051ab01ab2b6ac/demo/progress-bar-basic-demos.html#L43)):*
<details><summary><i>Previously, limonte (Limon Monte) wrote…</i></summary><blockquote>

Why this demo example was removed?
</blockquote></details>

Because we decided to move indeterminate animation to the theme.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-progress-bar/16)*

**Comment by tonygoldcrest** [comment]
Review status: 0 of 6 files reviewed at latest revision, 7 unresolved discussions.

---

*[vaadin-progress-bar.html, line 83 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-progress-bar/16#-Kw49ZQCxUDRXsj_NY7a:-Kw4DF0GSj-rrPpL95tl:b-896fix) ([raw file](https://github.com/vaadin/vaadin-progress-bar/blob/93b2520d5cb036dff07ef5fd8a1f27a46f5d3fb3/vaadin-progress-bar.html#L83)):*
<details><summary><i>Previously, limonte (Limon Monte) wrote…</i></summary><blockquote>

add `@mixes Vaadin.ThemableMixin`
</blockquote></details>

Done.

---

*[test/vaadin-progress-bar.html, line 7 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-progress-bar/16#-Kw49j7XF6cPbNQauH3X:-Kw4D8a6cShv07oEd_LK:b-896fix) ([raw file](https://github.com/vaadin/vaadin-progress-bar/blob/93b2520d5cb036dff07ef5fd8a1f27a46f5d3fb3/test/vaadin-progress-bar.html#L7)):*
<details><summary><i>Previously, limonte (Limon Monte) wrote…</i></summary><blockquote>

Why this import was added?
</blockquote></details>

Done.

---

*[test/vaadin-progress-bar.html, line 34 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-progress-bar/16#-Kw49lSnk2Sd2HEpP8lJ:-Kw4D9PLw2yiDVyWjy62:b-896fix) ([raw file](https://github.com/vaadin/vaadin-progress-bar/blob/93b2520d5cb036dff07ef5fd8a1f27a46f5d3fb3/test/vaadin-progress-bar.html#L34)):*
<details><summary><i>Previously, limonte (Limon Monte) wrote…</i></summary><blockquote>

remove
</blockquote></details>

Done.

---

*[test/vaadin-progress-bar.html, line 36 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-progress-bar/16#-Kw49q7TYQ1JoywCTNtM:-Kw4DCmWaSbtBeINDBnn:b-896fix) ([raw file](https://github.com/vaadin/vaadin-progress-bar/blob/93b2520d5cb036dff07ef5fd8a1f27a46f5d3fb3/test/vaadin-progress-bar.html#L36)):*
<details><summary><i>Previously, limonte (Limon Monte) wrote…</i></summary><blockquote>

> progress.shadowRoot.querySelector('[part="value"]')

This should be assigned to the `value` variable in the `beforeEach`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-progress-bar/16)*

**Comment by limonte** [comment]
:lgtm:

---

Reviewed 1 of 3 files at r1, 3 of 5 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-progress-bar/16#-:-Kw4G-7quDS4oiYoTarv:bnfp4nl)*

**Comment by tomivirkki** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[vaadin-progress-bar.html, line 32 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-progress-bar/16#-Kw4HICuVPasDlypJ9E2:-Kw4HICuVPasDlypJ9E3:b-vomu7i) ([raw file](https://github.com/vaadin/vaadin-progress-bar/blob/829180e40b03e383bdf285c11a00ed28aa5d60db/vaadin-progress-bar.html#L32)):*
> ```HTML
>         display: block;
>         height: 3px;
>         margin: 8px 0;
> ```

Is this needed for something? Remove, if not

---

*[vaadin-progress-bar.html, line 33 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-progress-bar/16#-Kw4HLhhf9-eQuZQt7qr:-Kw4HLhhf9-eQuZQt7qs:b-vomu7i) ([raw file](https://github.com/vaadin/vaadin-progress-bar/blob/829180e40b03e383bdf285c11a00ed28aa5d60db/vaadin-progress-bar.html#L33)):*
> ```HTML
>         height: 3px;
>         margin: 8px 0;
>         overflow: hidden;
> ```

Is this needed for something? Remove, if not

---

*[vaadin-progress-bar.html, line 34 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-progress-bar/16#-Kw4HTBHNTlf6bgabWsy:-Kw4HTBHNTlf6bgabWsz:b-vomu7i) ([raw file](https://github.com/vaadin/vaadin-progress-bar/blob/829180e40b03e383bdf285c11a00ed28aa5d60db/vaadin-progress-bar.html#L34)):*
> ```HTML
>         margin: 8px 0;
>         overflow: hidden;
>         position: relative;
> ```

Is this needed for something? Remove, if not

---

*[vaadin-progress-bar.html, line 39 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-progress-bar/16#-Kw4HU1f2DYpsOjv-2TS:-Kw4HU1f2DYpsOjv-2TT:b-vomu7i) ([raw file](https://github.com/vaadin/vaadin-progress-bar/blob/829180e40b03e383bdf285c11a00ed28aa5d60db/vaadin-progress-bar.html#L39)):*
> ```HTML
>       [part="bar"] {
>         height: 100%;
>         position: absolute;
> ```

Is this needed for something? Remove, if not

---

*[vaadin-progress-bar.html, line 40 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-progress-bar/16#-Kw4HUdClPxjSB5sC-8O:-Kw4HUdClPxjSB5sC-8P:b-9aialu) ([raw file](https://github.com/vaadin/vaadin-progress-bar/blob/829180e40b03e383bdf285c11a00ed28aa5d60db/vaadin-progress-bar.html#L40)):*
> ```HTML
>         height: 100%;
>         position: absolute;
>         width: 100%;
> ```

Is this needed for something? Remove

---

*[vaadin-progress-bar.html, line 45 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-progress-bar/16#-Kw4HWAicvI9uoQ3PGK9:-Kw4HWAicvI9uoQ3PGKA:b-vomu7i) ([raw file](https://github.com/vaadin/vaadin-progress-bar/blob/829180e40b03e383bdf285c11a00ed28aa5d60db/vaadin-progress-bar.html#L45)):*
> ```HTML
>       [part="value"] {
>         height: 100%;
>         position: absolute;
> ```

Is this needed for something? Remove, if not

---

*[vaadin-progress-bar.html, line 47 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-progress-bar/16#-Kw4HX12vVt8JKa5ctQl:-Kw4HX12vVt8JKa5ctQm:b-vomu7i) ([raw file](https://github.com/vaadin/vaadin-progress-bar/blob/829180e40b03e383bdf285c11a00ed28aa5d60db/vaadin-progress-bar.html#L47)):*
> ```HTML
>         position: absolute;
>         transform-origin: 0 50%;
>         width: 100%;
> ```

Is this needed for something? Remove, if not

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-progress-bar/16)*

**Comment by tonygoldcrest** [comment]
Review status: 4 of 6 files reviewed at latest revision, 8 unresolved discussions.

---

*[vaadin-progress-bar.html, line 32 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-progress-bar/16#-Kw4HICuVPasDlypJ9E2:-Kw4S58TvklHhPhWW-SL:b-896fix) ([raw file](https://github.com/vaadin/vaadin-progress-bar/blob/829180e40b03e383bdf285c11a00ed28aa5d60db/vaadin-progress-bar.html#L32)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Is this needed for something? Remove, if not
</blockquote></details>

Done.

---

*[vaadin-progress-bar.html, line 33 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-progress-bar/16#-Kw4HLhhf9-eQuZQt7qr:-Kw4S4Cf-a1T3rTNP7eQ:b-896fix) ([raw file](https://github.com/vaadin/vaadin-progress-bar/blob/829180e40b03e383bdf285c11a00ed28aa5d60db/vaadin-progress-bar.html#L33)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Is this needed for something? Remove, if not
</blockquote></details>

Done.

---

*[vaadin-progress-bar.html, line 34 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-progress-bar/16#-Kw4HTBHNTlf6bgabWsy:-Kw4S4VmbnJ4mjGnD2Ez:b-896fix) ([raw file](https://github.com/vaadin/vaadin-progress-bar/blob/829180e40b03e383bdf285c11a00ed28aa5d60db/vaadin-progress-bar.html#L34)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Is this needed for something? Remove, if not
</blockquote></details>

Done.

---

*[vaadin-progress-bar.html, line 39 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-progress-bar/16#-Kw4HU1f2DYpsOjv-2TS:-Kw4S3fb9Pbx7H_2uDXl:b-896fix) ([raw file](https://github.com/vaadin/vaadin-progress-bar/blob/829180e40b03e383bdf285c11a00ed28aa5d60db/vaadin-progress-bar.html#L39)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Is this needed for something? Remove, if not
</blockquote></details>

Done.

---

*[vaadin-progress-bar.html, line 40 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-progress-bar/16#-Kw4HUdClPxjSB5sC-8O:-Kw4S3MtQ4c9hd7Py2Kh:b-896fix) ([raw file](https://github.com/vaadin/vaadin-progress-bar/blob/829180e40b03e383bdf285c11a00ed28aa5d60db/vaadin-progress-bar.html#L40)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Is this needed for something? Remove
</blockquote></details>

Done.

---

*[vaadin-progress-bar.html, line 45 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-progress-bar/16#-Kw4HWAicvI9uoQ3PGK9:-Kw4S2byrLB0bobsHjb4:b-896fix) ([raw file](https://github.com/vaadin/vaadin-progress-bar/blob/829180e40b03e383bdf285c11a00ed28aa5d60db/vaadin-progress-bar.html#L45)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Is this needed for something? Remove, if not
</blockquote></details>

Done.

---

*[vaadin-progress-bar.html, line 47 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-progress-bar/16#-Kw4HX12vVt8JKa5ctQl:-Kw4S30ZXLM6_mE1mW35:b-896fix) ([raw file](https://github.com/vaadin/vaadin-progress-bar/blob/829180e40b03e383bdf285c11a00ed28aa5d60db/vaadin-progress-bar.html#L47)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Is this needed for something? Remove, if not
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-progress-bar/16)*

**Comment by tomivirkki** [comment]
*[vaadin-progress-bar.html, line 71 at r5](https://reviewable.io:443/reviews/vaadin/vaadin-progress-bar/16#-Kw4WnuKu-nbggnj7U_Z:-Kw4WnuKu-nbggnj7U__:b5qve4u) ([raw file](https://github.com/vaadin/vaadin-progress-bar/blob/6a4454a12caa2572c2125b217bf2ac04fb7168cd/vaadin-progress-bar.html#L71)):*
> ```HTML
>        * Part name | Description | Theme for Element
>        * ----------------|----------------|----------------
>        * `bar` | Progress-bar's background | vaadin-progress-bar
> ```

This element doesn't have any internal sub-elements so no "Theme for Element" column needed. Example: https://github.com/vaadin/vaadin-text-field/blob/master/vaadin-text-field.html#L152

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-progress-bar/16)*

**Comment by tonygoldcrest** [comment]
Review status: 4 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-progress-bar.html, line 71 at r5](https://reviewable.io:443/reviews/vaadin/vaadin-progress-bar/16#-Kw4WnuKu-nbggnj7U_Z:-Kw4YKXKadSambu2XWIe:b-896fix) ([raw file](https://github.com/vaadin/vaadin-progress-bar/blob/6a4454a12caa2572c2125b217bf2ac04fb7168cd/vaadin-progress-bar.html#L71)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

This element doesn't have any internal sub-elements so no "Theme for Element" column needed. Example: https://github.com/vaadin/vaadin-text-field/blob/master/vaadin-text-field.html#L152
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-progress-bar/16)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 1 of 3 files at r1, 2 of 5 files at r3, 1 of 2 files at r4, 1 of 2 files at r5, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-progress-bar/16#-:-Kw4dXZSLquOe9YzqM7T:bnfp4nl)*

**Comment by manolo** [comment]
:lgtm:

---

Reviewed 1 of 3 files at r1, 1 of 2 files at r2, 2 of 5 files at r3, 1 of 2 files at r4, 1 of 2 files at r5, 1 of 1 files at r6.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-progress-bar/16#-:-Kw4nEYil5Vu9hDv20Wf:bnfp4nl)*

**Pull request merged**
