### PR TITLE
Drop progress-circle.

### PR DESCRIPTION
**Pull request by tonygoldcrest**
Connects to #11.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-progress-bar/13)

### CODE REVIEW

**Comment by limonte** [comment]
If you run `polymer serve` it will still show `progress-bar-circle`: 



That's because you need to regenerate `analysis.json` manually by running:

```
polymer analyze --input vaadin-progress-bar.html > analysis.json
```

Put that update in a separated commit with name "Bump analysis.json"

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-progress-bar/13#-:-Kva5FjaX-C5rigIcqek:bu9u73i)*

**Comment by tomivirkki** [comment]
Readme still has mentions of -circle

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-progress-bar/13#-:-KvabnOvk401xKsqo_XV:b-9xbdls)*

**Comment by limonte** [comment]
:lgtm:

---

Review status: 4 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-progress-bar/13#-:-KvasV-y0Pny82sMPASJ:bnfp4nl)*

**Comment by limonte** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-progress-bar/13)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r1, 2 of 2 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-progress-bar/13#-:-Kvasktzpe6NpJOjqkDb:bnfp4nl)*

**Pull request merged**
