### PR TITLE
P3 preview dev

### LINKED ISSUE #41: Ensure Polymer 3 Modulizer compatibility
See “Generic steps” at vaadin/components-team-tasks#326

### PR DESCRIPTION
**Pull request by tomivirkki**
Fixes #41

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-progress-bar/43)

### CODE REVIEW

**Comment by web-padawan** [comment]
Review status: 0 of 13 files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[demo/progress-bar-basic-demos.html, line 1 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-progress-bar/43#-L8bkg79rn9-xTPU0208:-L8bkg79rn9-xTPU0209:be4t47) ([raw file](https://github.com/vaadin/vaadin-progress-bar/blob/6d216fb7fbd151c57ac0e140c4cc6a2f56e236e8/demo/progress-bar-basic-demos.html#L1)):*
> ```HTML
> <link rel="import" href="progress-bar-demo.html">
> ```

we have decided to convert the demo file to the `.js` and only load it in `index.html`in order to avoid these imports. See https://github.com/vaadin/vaadin-item/pull/28/files#diff-3e22c50371c76d64ea9738dbc46a6e57

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-progress-bar/43)*

**Comment by platosha** [comment]
Reviewed 13 of 13 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---

*[demo/index.html, line 18 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-progress-bar/43#-L8bkYst5sqa_AGbiNWP:-L8bkYst5sqa_AGbiNWQ:b-r3gc9) ([raw file](https://github.com/vaadin/vaadin-progress-bar/blob/6d216fb7fbd151c57ac0e140c4cc6a2f56e236e8/demo/index.html#L18)):*
> ```HTML
>   <link rel="import" href="../../vaadin-button/vaadin-button.html">
>   <link rel="import" href="../vaadin-progress-bar.html">
>   
> ```

Nit: extra whitespace.

---

*[demo/progress-bar-basic-demos.html, line 1 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-progress-bar/43#-L8bkhteyKHrUOatST-B:-L8bkhtfbpJ5rs-ZrIdx:b-uscsl0) ([raw file](https://github.com/vaadin/vaadin-progress-bar/blob/6d216fb7fbd151c57ac0e140c4cc6a2f56e236e8/demo/progress-bar-basic-demos.html#L1)):*
> ```HTML
> <link rel="import" href="progress-bar-demo.html">
> ```

BTW Maybe not a good idea to modify -demos.html.

As it seems for me, the intention behind the demo setup we have is to get rid of HTML imports here...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-progress-bar/43)*

**Comment by yuriy-fix** [comment]
Reviewed 13 of 13 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-progress-bar/43)*

**Comment by tomivirkki** [comment]
Review status: 6 of 12 files reviewed at latest revision, 3 unresolved discussions.

---

*[demo/index.html, line 18 at r1](https://beta.reviewable.io/reviews/vaadin/vaadin-progress-bar/43#-L8bkYst5sqa_AGbiNWP:-L8fadiM7CzlqKaZtJ7x:b-896fix) ([raw file](https://github.com/vaadin/vaadin-progress-bar/blob/6d216fb7fbd151c57ac0e140c4cc6a2f56e236e8/demo/index.html#L18)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

Nit: extra whitespace.
</blockquote></details>

Done.

---

*[demo/progress-bar-basic-demos.html, line 1 at r1](https://beta.reviewable.io/reviews/vaadin/vaadin-progress-bar/43#-L8bkg79rn9-xTPU0208:-L8fafEBA3qx9ALHi2nW:b-896fix) ([raw file](https://github.com/vaadin/vaadin-progress-bar/blob/6d216fb7fbd151c57ac0e140c4cc6a2f56e236e8/demo/progress-bar-basic-demos.html#L1)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

we have decided to convert the demo file to the `.js` and only load it in `index.html`in order to avoid these imports. See https://github.com/vaadin/vaadin-item/pull/28/files#diff-3e22c50371c76d64ea9738dbc46a6e57
</blockquote></details>

Done.

---

*[demo/progress-bar-basic-demos.html, line 1 at r1](https://beta.reviewable.io/reviews/vaadin/vaadin-progress-bar/43#-L8bkhteyKHrUOatST-B:-L8fagGoBHSvxxdAcAxc:b-896fix) ([raw file](https://github.com/vaadin/vaadin-progress-bar/blob/6d216fb7fbd151c57ac0e140c4cc6a2f56e236e8/demo/progress-bar-basic-demos.html#L1)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

BTW Maybe not a good idea to modify -demos.html.

As it seems for me, the intention behind the demo setup we have is to get rid of HTML imports here...
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-progress-bar/43)*

**Comment by web-padawan** [comment]
Reviewed 7 of 9 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-progress-bar/43)*

**Comment by limonte** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[.npmignore, line 7 at r2](https://beta.reviewable.io/reviews/vaadin/vaadin-progress-bar/43#-L8fexLF07u5WglP8odd:-L8fexLF07u5WglP8ode:b-5elx1h) ([raw file](https://github.com/vaadin/vaadin-progress-bar/blob/5976c08849a39907ad44995cd700c107011f9490/.npmignore#L7)):*
> ```
> .gemini.yml
> wct.conf.js
> .analysis.json
> ```

remove `.`

---

*[theme/lumo/vaadin-progress-bar-lumo.html, line 1 at r2](https://beta.reviewable.io/reviews/vaadin/vaadin-progress-bar/43#-L8ff3WIAJBp3INi8bke:-L8ff3WJ6ZrGDvHAi0Z5:boq4fbj) ([raw file](https://github.com/vaadin/vaadin-progress-bar/blob/5976c08849a39907ad44995cd700c107011f9490/theme/lumo/vaadin-progress-bar-lumo.html#L1)):*
> ```HTML
> <link rel="import" href="../../../vaadin-lumo-styles/color.html">
> ```

I don't like this trick with `theme/lumo/vaadin-progress-bar-lumo.html`:

1. naming is bad, keyword `lumo` already presents in the folder structure
2. `git blame` practically becomes useless since for the whole file the latest commit will be this one

Not a blocker.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-progress-bar/43)*

**Comment by limonte** [comment]
:lgtm:

---

Reviewed 5 of 14 files at r1, 5 of 9 files at r2, 3 of 4 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-progress-bar/43#-:-L8fiayR-uPcggbLzLVc:bnfp4nl)*

**Comment by tomivirkki** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[.npmignore, line 7 at r2](https://beta.reviewable.io/reviews/vaadin/vaadin-progress-bar/43#-L8fexLF07u5WglP8odd:-L8fhSw00hu9erKg7om-:b-896fix) ([raw file](https://github.com/vaadin/vaadin-progress-bar/blob/5976c08849a39907ad44995cd700c107011f9490/.npmignore#L7)):*
<details><summary><i>Previously, limonte (Limon Monte) wrote…</i></summary><blockquote>

remove `.`
</blockquote></details>

Done.

---

*[theme/lumo/vaadin-progress-bar-lumo.html, line 1 at r2](https://beta.reviewable.io/reviews/vaadin/vaadin-progress-bar/43#-L8ff3WIAJBp3INi8bke:-L8fiSPkAKq8gGPHxnOL:bjthp8e) ([raw file](https://github.com/vaadin/vaadin-progress-bar/blob/5976c08849a39907ad44995cd700c107011f9490/theme/lumo/vaadin-progress-bar-lumo.html#L1)):*
<details><summary><i>Previously, limonte (Limon Monte) wrote…</i></summary><blockquote>

I don't like this trick with `theme/lumo/vaadin-progress-bar-lumo.html`:

1. naming is bad, keyword `lumo` already presents in the folder structure
2. `git blame` practically becomes useless since for the whole file the latest commit will be this one

Not a blocker.
</blockquote></details>

We evaluated other options but this makes the most sense. This "trick" is required for the P3 version.

1. Agree, renamed to -styles.html
2. Done. (used git mv)

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-progress-bar/43)*

**Comment by platosha** [comment]
:lgtm:

---

Reviewed 4 of 9 files at r2, 3 of 4 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-progress-bar/43#-:-L8fmcT9B5gL02Yg7BdX:bnfp4nl)*

**Pull request merged**
