### PR TITLE
Set normalized value to 1 in case of wrong bounds.

### PR DESCRIPTION
**Pull request by tonygoldcrest**
Connects to #11

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-progress-bar/19)

### CODE REVIEW

**Comment by manolo** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-progress-mixin.html, line 75 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-progress-bar/19#-Kw8s5Hi5jxv6y3jMfZo:-Kw8s5Hjp1-h0KI5AWOz:b-k19f10) ([raw file](https://github.com/vaadin/vaadin-progress-bar/blob/ff3d2677964ca3bc530dbd31f438d5c58037c802/vaadin-progress-mixin.html#L75)):*
> ```HTML
>        * Percent of current progress relative to whole progress bar (max - min)
>        */
>       _normalizeValue(value, min, max) {
> ```

I see this algo a little bit complex, you might simplify it to 
`return Math.min(Math.max((value || 0 - min) / (max - min), 0), 1)` 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-progress-bar/19)*

**Comment by tonygoldcrest** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-progress-mixin.html, line 75 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-progress-bar/19#-Kw8s5Hi5jxv6y3jMfZo:-Kw9U7Iv4Te7EPfao8l8:b-l40egj) ([raw file](https://github.com/vaadin/vaadin-progress-bar/blob/ff3d2677964ca3bc530dbd31f438d5c58037c802/vaadin-progress-mixin.html#L75)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

I see this algo a little bit complex, you might simplify it to 
`return Math.min(Math.max((value || 0 - min) / (max - min), 0), 1)` 

</blockquote></details>

This will not work as expected:
1) Let's imagine we have such function:
```
function a (value, min, max) {
return Math.min(Math.max((value || 0 - min) / (max - min), 0), 1);
}
```
Let's call this function
`a(undefined, -2, 2) // => 0.5`, but we expected 0 because value is undefined.
It's because of operators priority, `-` sign has more priority than `||`.
Ok, let's fix that
```
function a (value, min, max) {
return Math.min(Math.max(((value || 0) - min) / (max - min), 0), 1);
}
```
and call again:
`a(2,2,2) // => NaN`, but we expected 1, because min and max are the same.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-progress-bar/19)*

**Comment by tonygoldcrest** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-progress-mixin.html, line 75 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-progress-bar/19#-Kw8s5Hi5jxv6y3jMfZo:-Kw9XvB6U_Hi6I8WktjZ:b-p8b1xt) ([raw file](https://github.com/vaadin/vaadin-progress-bar/blob/ff3d2677964ca3bc530dbd31f438d5c58037c802/vaadin-progress-mixin.html#L75)):*
<details><summary><i>Previously, Toshegg wrote…</i></summary><blockquote>

This will not work as expected:
1) Let's imagine we have such function:
```
function a (value, min, max) {
return Math.min(Math.max((value || 0 - min) / (max - min), 0), 1);
}
```
Let's call this function
`a(undefined, -2, 2) // => 0.5`, but we expected 0 because value is undefined.
It's because of operators priority, `-` sign has more priority than `||`.
Ok, let's fix that
```
function a (value, min, max) {
return Math.min(Math.max(((value || 0) - min) / (max - min), 0), 1);
}
```
and call again:
`a(2,2,2) // => NaN`, but we expected 1, because min and max are the same.
</blockquote></details>

In this case I doubt that it's simplification of the code.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-progress-bar/19)*

**Comment by manolo** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-progress-mixin.html, line 75 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-progress-bar/19#-Kw8s5Hi5jxv6y3jMfZo:-Kw9lYylKiLHeYGL6TBG:bp7rybq) ([raw file](https://github.com/vaadin/vaadin-progress-bar/blob/ff3d2677964ca3bc530dbd31f438d5c58037c802/vaadin-progress-mixin.html#L75)):*
<details><summary><i>Previously, Toshegg wrote…</i></summary><blockquote>

In this case I doubt that it's simplification of the code.
</blockquote></details>

I see, I didn't consider that min could be negative probably. 
So can you add a couple of unit tests for those cases, so a we dont break the algo in the future.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-progress-bar/19)*

**Comment by tonygoldcrest** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-progress-mixin.html, line 75 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-progress-bar/19#-Kw8s5Hi5jxv6y3jMfZo:-Kw9saPmUuJmogmu_LiW:b-i5uoyf) ([raw file](https://github.com/vaadin/vaadin-progress-bar/blob/ff3d2677964ca3bc530dbd31f438d5c58037c802/vaadin-progress-mixin.html#L75)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

I see, I didn't consider that min could be negative probably. 
So can you add a couple of unit tests for those cases, so a we dont break the algo in the future.
</blockquote></details>

I've already added some tests which cover these cases.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-progress-bar/19)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-progress-bar/19#-:-Kw9swvyjuKBGGofMPYs:bnfp4nl)*

**Comment by manolo** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-progress-bar/19#-:-KwADCqAQ8S_nsBmRUwG:bnfp4nl)*

**Pull request merged**
