### PR TITLE
Added the indeterminate property to the vaadin-progress-bar.

### LINKED ISSUE #26: DX finding: Add indeterminate property
Add property `indeterminate` that reflects to attribute.

Adapt the following set of styles to the default theme: https://github.com/vaadin/vaadin-progress-bar/issues/23#issuecomment-337658990 (additionally, value might need to have `width: 100%`)

Document the new state attribute and add a test

### PR DESCRIPTION
**Pull request by vicsstar**
Fixes #26

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-progress-bar/27)

### CODE REVIEW

**Comment by tomivirkki** [comment]
*[vaadin-progress-bar.html, line 35 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-progress-bar/27#-Kxr937IJoajtZBGlFbI:-Kxr937JQ7ogD5ednhXw:bxzd1f1) ([raw file](https://github.com/vaadin/vaadin-progress-bar/blob/d62ae49da46069c4290ca60571adbf47b974d4c8/vaadin-progress-bar.html#L35)):*
> ```HTML
> 
>       :host([indeterminate]) [part="bar"] {
>         overflow: hidden;
> ```

Might be cleaner to have the bar overflow hidden regardless of the state.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-progress-bar/27)*

**Comment by vicsstar** [comment]
*[vaadin-progress-bar.html, line 35 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-progress-bar/27#-Kxr937IJoajtZBGlFbI:-KxrRLOTqsYWAWGZ_zcZ:b-896fix) ([raw file](https://github.com/vaadin/vaadin-progress-bar/blob/d62ae49da46069c4290ca60571adbf47b974d4c8/vaadin-progress-bar.html#L35)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Might be cleaner to have the bar overflow hidden regardless of the state.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-progress-bar/27)*

**Comment by tomivirkki** [comment]
:lgtm: 

---

Reviewed 4 of 5 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-progress-bar/27#-:-KxrRvIDevq1qeHJu7iY:bg7igkv)*

**Comment by yuriy-fix** [comment]
:lgtm:

---

Reviewed 4 of 5 files at r1, 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-progress-bar/27#-:-KxrejTszJ58y9hB8opc:bnfp4nl)*

**Pull request merged**
